# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

platform :ios do

  lane :init_config do
    match(type: "appstore")
    match(type: "development")
  end

  lane :get_prov do
    register_devices(
      devices_file: "./devices.txt",
      username: "lazaro.shev@gmail.com"
    )
    get_provisioning_profile(
      development: true,
      app_identifier: "br.com.xsistemas.DeliveryHair",
      username: "lazaro.shev@gmail.com"
    )
    get_provisioning_profile(
      app_identifier: "br.com.xsistemas.DeliveryHair",
      username: "lazaro.shev@gmail.com"
    )
  end

  lane :publish_dev do
    sync_code_signing(
      type: "development",
      username: "lazaro.shev@gmail.com"
    )
    increment_build_number
    build_app(
      scheme: "DeliveryHair",
      workspace: "DeliveryHair.xcworkspace",
      include_bitcode: true,
      clean: true,
      configuration: "Debug",
      export_method: "development"
    )
    hockey(
      api_token: "31f01a42db3c4313a5daf3ee5ae9835c",
      notes: "this build was uploaded with fastlane!",
      notify: "1"
    )
  end

  lane :prod do
    register_devices(
      devices_file: "./devices.txt",
      username: "lazaro.shev@gmail.com"
    )
    get_provisioning_profile(
      development: true,
      app_identifier: "br.com.xsistemas.DeliveryHair",
      username: "lazaro.shev@gmail.com"
    )
    sync_code_signing(
      type: "development",
      username: "lazaro.shev@gmail.com"
    )
    increment_build_number
    build_app(
      scheme: "DeliveryHair",
      workspace: "DeliveryHair.xcworkspace",
      include_bitcode: true,
      clean: true,
      configuration: "Release",
      export_method: "appstore"
    )
    upload_to_testflight(
      username: "lazaro.shev@gmail.com",
      app_identifier: "br.com.xsistemas.DeliveryHair",
      ipa: "./"
    )
  end

end
